# Custom file for zlib, from jdcr. 
SUMMARY="Assignment_2"
DESCRIPTION="zlib-library for compression. this library is for compression and for sourcing"

# closed means internal and it doesnt check any file
# in source code. 
LICENSE = "CLOSED"

# important as it comes under library. it provides headers. 
SECTION = "libs"
BP_ORG_NAME="zlib-${PV}"

# The source tarball needs to be .gz as only the .gz ends up in fossils/
# ttps://zlib.net/${BP}.tar.gz ${BP} = zlib-jdcr, but there is nothing by this name
SRC_URI = "https://zlib.net/${BP_ORG_NAME}.tar.gz \
           file://run-ptest \
           "
UPSTREAM_CHECK_URI = "http://zlib.net/"

# sha256 of first file given in SRC_URI
# checked version SHA from website.
SRC_URI[sha256sum] = "bb329a0a2cd0274d05519d61c667c062e06990d72e125ee2dfa8de64f0119d16"

# in SRC_URI, first is key, second is to be replaced with
PREMIRRORS:append = " https://zlib.net/ https://zlib.net/fossils/"

#--------------------------------------------------------------#
# default S = ${WORKDIR}/${BP} 
# which would resolve to ${WORKDIR}/zlib_jdcr_1.3.2, 
# but tar_ball extracts into zlib_1.3.2 folder. so 
# resolving name issue below. 
S = "${WORKDIR}/${BP_ORG_NAME}"
#--------------------------------------------------------------#


#--------------------------------------------------------------#
# do_configuring and building the makefile
# 
# B = ${WORKDIR}/build 
# and in backend, bitbake does 
# do_configure[dirs] = ${B}. so before running do_configure step, 
# it cd into ${B}
B = "${WORKDIR}/build-jdcr"
do_configure[cleandirs] += "${B}"

# configure has no output-directory option.
# It writes Makefile, zlib.pc, zconf.h and configure.log 
# into whatever directory you run it from.
do_configure() {
	LDCONFIG=true;
  ${S}/configure --prefix=${prefix} --shared --libdir=${libdir} --uname=GNU
}
# after this, B = ${WORKDIR}/build-jdcr will be populated. 
#--------------------------------------------------------------#

#----------------------------------------------------------------# 
# do_compile step 

# below will change to B, and trigger the makefile which 
# was being generated by configure script. 
do_compile() {
  oe_runmake shared
}
# after this step, B=${WORKDIR}/build-jdcr is populated with object file. 

#----------------------------------------------------------------# 
# do_install step 
do_install() {
	oe_runmake DESTDIR=${D} install
}
# ${D} would be populated. 